# .streamlit/secrets.toml

[aws]
AWS_DEFAULT_REGION = "us-east-1"
AWS_ACCESS_KEY_ID="AKxxxxxxxxxx"
AWS_SECRET_ACCESS_KEY="Xxxxxxxxx"

[mongo_db]
url = "mongodb://mongo:27017"
db = "vcons"
collection = "vcons"

[openai]
testing_key = "sk-proj-xxxxxxxxxxxxxxxx"
api_key = "sk-proj-xxxxxxxxxxxxxxxxx"
organization = "org-xxxxxxxxxx"
project = "proj_xxxxxxxxx"
vector_store_name = "vcons"
assistant_id = "asst_xxxxxxxxxxxxxx"

[elasticsearch]
url = "https://localhost:9200"
username = "elastic"
password = "xxxxxxxx"
 
[conserver]
api_url = "http://api:8000"
auth_token = "123456780"